version: '3.8'

services:
  app:
    image: demo-rest-api-app:latest
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    networks:
      - backend
    restart: always
    links:
      - postgres:postgres
      - mongo:mongo
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: api
      POSTGRES_DB: demo
      # see: https://stackoverflow.com/a/28406007
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
    
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      MONGO_INITDB_DATABASE: demo
      MONGO_INITDB_ROOT_USERNAME: api
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8081:80
    networks:
      - backend
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - postgres:postgres
    depends_on:
      - postgres

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
  mongo-data:
  pgadmin-data:
